idf_component_register(
    SRCS
        "testboard.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_timer
        esp_http_client
        esp_lcd
        driver
        spi_flash
        espressif__esp-sr
        json
        lwip
        esp-tls
        log
        wakeword
    EMBED_TXTFILES
        "certs/rbots_root_ca.pem"
)
